### ISSUE TITLE
Building a Fork with new features.

### ISSUE THREAD

**Issue by DoryZi** [Altaba77/ngx-walkthrough#2]
HI,

Cool Work man! 

I would like to build on this module, to make it even more great.
I started making some changes to this module for example:
-  I wanted to make selected items sometimes interactive, so user can use the selected element not only see a tip
- to add the ability to highlight multiple items
- Few other changes and enhancement and a few other things. 

I've forked this repo, and updated most npm modules.
Now I'm trying to run `npm run build` but it gives me a some circular reference, seems it runs out of stack calls:

`: RangeError: Maximum call stack size exceeded
    at getLineStarts (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:6085:27)
    at Object.getLineAndCharacterOfPosition (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:6113:50)
    at getLineOfLocalPosition (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:10262:19)
    at positionsAreOnSameLine (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:10978:13)
    at Object.rangeEndIsOnSameLineAsRangeStart (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:10973:16)
    at needsIndentation (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:73203:24)
    at emitBinaryExpression (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:71844:40)
    at pipelineEmitExpression (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:70991:49)
    at emitNodeWithSourceMap (/home/doryz/IdeaProjects/ngx-walkthrough/node_modules/typescript/lib/typescript.js:68279:21)
`
Have you gotten this error before?
If so how do you suggest to solve it?
have you had any issues running the build?
Any guidelines on how to build?
If you help me, once I finish I'll send you a PR into this lib.

Can that work? Can you help ?
I'm using node 8.9.3 what version of node and npm did you use?

**Comment by Altaba77** [comment]
Hello,

To build the project you can refer directly to the "readme" of the template I used:
https://github.com/robisim74/angular-library-starter

Normally you just have to run the command "npm run build" to build the project as you did.

Your error look like the error you get when there is an Input() in your file and in the set of the input you call the get link to this Input instead of the private property.

example that failed:

 _allowDay: boolean;
    get allowDay(): boolean {
        return this._allowDay;
    }
    set allowDay(value: boolean) {
        this.allowDay = value;
    }

example that compile:

 _allowDay: boolean;
    get allowDay(): boolean {
        return this._allowDay;
    }
    set allowDay(value: boolean) {
        this.**_**allowDay = value;
    }

But I cannot be sure without look into your code.

**Comment by DoryZi** [comment]
I actaully made no changes, just ran npm isntall, and deleted the dist folder..
Zero code changes.
What version node and npm you use to build?

**Comment by Altaba77** [comment]
node 9.8.0
npm 5.6.0

**Comment by Altaba77** [comment]
I tried to download the zip of the lib on another computer that mine, and "npm install" followed by "npm run build" works without any error. Did the update of node made a difference?

**Comment by Altaba77** [comment]
I think I know what is the problem, the icons wrote in base64 cause the generation of js files too big. The solution could be to use directly the png icons instead of base64 string. But I get trouble with icons path when I use the lib in a project, that is why I choose the base64.
Update node may solved the problem too, anyway I will try to remove this base64 icons of the lib.

**Comment by DoryZi** [comment]
oh ok, you're using node 9.8.0..I use node 8.9.3
Small suggestion, don't use node 9.x, use node 8x, as that is LTS (Long term support)..
I always try to work with lts, I will try node 9 , and see what happens.

**Comment by DoryZi** [comment]
Here is the first pr, 
https://github.com/Altaba77/ngx-walkthrough/pull/3

Btw, it's a good idea to remove all those inline things, to external files and fix the build process, it's really hard to see with so much things in it..anyhow, I started a small re-factor plus new support :)
